# Generated by Django 2.2.5 on 2020-02-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_tasks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Comapny', 'Company'), ('individual', 'individual'), ('Family', 'Family')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='send_by_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='with_battery',
            field=models.BooleanField(default=False),
        ),
    ]
