# Generated by Django 3.0.3 on 2020-03-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200229_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
