# Generated by Django 3.0.3 on 2020-03-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200327_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='ac_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='cancellation',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='data_collection',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='installation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='offer_created',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='order_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='photo_counter_cabinet',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='photo_of_counter',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='photo_roof_access',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='power_of_attorney',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='project_planning_created',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='video_counter',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='with_battery',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
