# Generated by Django 3.0.3 on 2020-03-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200327_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='manufacturer2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer'),
        ),
    ]
