# Generated by Django 3.0.3 on 2020-03-27 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200327_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasks',
            name='todo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='message',
            field=models.TextField(),
        ),
    ]
