# Generated by Django 3.0.3 on 2020-03-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20200327_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='todo_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
