# Generated by Django 3.0.3 on 2020-03-27 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_tasks_todo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='todo_date',
            field=models.DateField(blank=True, null=True, verbose_name='Complete Before'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='todo_time',
            field=models.TimeField(blank=True, default=datetime.time(16, 0), verbose_name=''),
        ),
    ]
