# Generated by Django 3.0.3 on 2020-03-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20200327_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='callnotes',
            name='created',
            field=models.DateField(null=True),
        ),
    ]
