# Generated by Django 3.0.3 on 2020-03-29 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_attachments_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callnotes',
            name='notes',
            field=models.CharField(max_length=1000, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='offer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='offer id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='place',
            field=models.CharField(max_length=255, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postcode',
            field=models.CharField(max_length=255, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Comapny', 'Company'), ('individual', 'individual'), ('Family', 'Family')], max_length=100, null=True, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=500, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='ac_mechanic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AC mechanic'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='ac_term',
            field=models.DateField(blank=True, null=True, verbose_name='AC Term'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='alignment',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='alignment'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='date_sent',
            field=models.DateField(blank=True, null=True, verbose_name='date sent'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='dc_mechanic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DC mechanic'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='dc_term',
            field=models.DateField(blank=True, null=True, verbose_name='DC Term'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='declined',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='declined'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='extra_details',
            field=models.TextField(blank=True, null=True, verbose_name='extra details'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='kwh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kw/H'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='module_area',
            field=models.FloatField(blank=True, default=0, help_text='Area in meter squared (m2)', null=True, validators=[django.core.validators.MinValueValidator(0, 'Should be above 0')], verbose_name='module area'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='module_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='module count'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='offer_by',
            field=models.CharField(choices=[('Email', 'Via Email'), ('Letter', 'Via Letter')], max_length=16, null=True, verbose_name='offer by'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='offer_date',
            field=models.DateField(blank=True, null=True, verbose_name='offer date'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='price_without_tax',
            field=models.FloatField(default=0, help_text='Price in Euro (€)', null=True, validators=[django.core.validators.MinValueValidator(0, 'Should be above 0')], verbose_name='price without tax'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='project_planning_created',
            field=models.BooleanField(blank=True, default=True, verbose_name='project planning created'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='reseller_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reseller name'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='roof_tilt',
            field=models.FloatField(blank=True, help_text='in Degrees', null=True, verbose_name='roof tilt'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='roof_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='roof type'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='watt',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='watt'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='with_battery',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='with battery'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Username'),
        ),
    ]
