# Generated by Django 3.0.3 on 2020-03-29 19:39

from django.db import migrations, models
import mainapp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20200329_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='upload',
            field=mainapp.fields.ContentTypeRestrictedFileField(null=True, upload_to='uploads/', verbose_name='Upload'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
    ]
