# Generated by Django 3.0.3 on 2020-03-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20200329_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_record', to='mainapp.Customer'),
        ),
    ]
