# Generated by Django 3.0.3 on 2020-04-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20200331_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='module_manufacturer',
            field=models.CharField(max_length=255, null=True, verbose_name='manufacturer'),
        ),
    ]
