# Generated by Django 3.0.3 on 2020-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20200421_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='project_planning_created',
            field=models.BooleanField(default=False, verbose_name='project planning created'),
        ),
    ]
