# Generated by Django 3.0.3 on 2020-04-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20200423_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='private',
            field=models.BooleanField(default=False, verbose_name='private'),
        ),
    ]
