# Generated by Django 3.0.3 on 2020-05-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_attachments_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='callnotes',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'high'), (1, 'medium'), (2, 'low')], default=1),
        ),
    ]
