# Generated by Django 3.0.3 on 2020-05-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20200510_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, default='N.A', max_length=120, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, default='N.A', max_length=20, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='N.A', max_length=20, unique=True, verbose_name='Phone'),
        ),
    ]
