# Generated by Django 3.0.3 on 2020-08-05 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_auto_20200518_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(verbose_name='company')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('surname', models.CharField(max_length=256, verbose_name='surname')),
                ('street', models.CharField(max_length=500, verbose_name='street')),
                ('postcode', models.CharField(max_length=255, verbose_name='postcode')),
                ('place', models.CharField(max_length=255, verbose_name='place')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
            ],
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(verbose_name='company')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('surname', models.CharField(max_length=256, verbose_name='surname')),
                ('street', models.CharField(max_length=500, verbose_name='street')),
                ('postcode', models.CharField(max_length=255, verbose_name='postcode')),
                ('place', models.CharField(max_length=255, verbose_name='place')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
            ],
        ),
        migrations.AlterField(
            model_name='attachmenttemplate',
            name='kind',
            field=models.CharField(choices=[('offer', 'offer'), ('offer_confirmation', 'offer confirmation'), ('install', 'install'), ('invoice', 'invoice')], max_length=32, unique=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='callnotes',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'Pending In Work'), (2, 'Finished')], default=1),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='todo_date',
            field=models.DateField(null=True, verbose_name='Complete Before'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='todo_time',
            field=models.TimeField(default=datetime.time(16, 0), verbose_name=''),
        ),
    ]
