# Generated by Django 3.0.3 on 2020-08-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20200805_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='company_name',
            field=models.CharField(max_length=500, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='company_name',
            field=models.CharField(max_length=500, verbose_name='company'),
        ),
    ]
