# Generated by Django 3.0.3 on 2020-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20200805_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='company_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='postcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='street',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='company_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='postcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='street',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='street'),
        ),
    ]
