# Generated by Django 3.0.3 on 2020-08-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20200805_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='ac_mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_purchases', to='mainapp.Mechanic'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='dc_mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dc_purchases', to='mainapp.Mechanic'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='reseller_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='mainapp.Reseller'),
        ),
    ]
